name: spreadsheet_decoder
description: A lightweight library for parsing and updating spreadsheet documents
version: 2.0.2
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: ">=2.12.0-259.14.beta <3.0.0"

dependencies:
  archive: ^3.0.0
  xml: ^5.0.1

dev_dependencies:
  path: ^1.8.0
  pedantic: ^1.10.0
  test: ^1.16.3
