name: spreadsheet_decoder
description: A lightweight library for parsing and updating spreadsheet documents
version: 1.3.0-nullsafety.0
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  archive: ^2.0.13
  xml: ^5.0.0-nullsafety.1

dev_dependencies:
  path: ^1.8.0-nullsafety.3
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
