name: spreadsheet_decoder
description: A lightweight library for parsing and updating spreadsheet documents
version: 2.0.0-nullsafety.0
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: ">=2.12.0-133.7.beta <3.0.0"

dependencies:
  archive: ^3.0.0-nullsafety.0
  xml: ^5.0.0-nullsafety.1

dev_dependencies:
  path: ^1.8.0-nullsafety.3
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.16
